### ISSUE TITLE
Done button on keyboard

### ISSUE THREAD

**Issue by trunglt8** [ozcanalasalvar/otpview#10]
how can detect done button on keyboard, help me Listener for this

**Comment by ozcanalasalvar** [comment]
onTextChange returns two parameters one of them current value that you type, other value is isCompleted that means user fill all boxes. You can handle this issue with using isCompleted parameter which is provied by onTextChange.

**Comment by trunglt8** [comment]
> onTextChange returns two parameters one of them current value that you type, other value is isCompleted that means user fill all boxes. You can handle this issue with using isCompleted parameter which is provied by onTextChange.

i used isCompleted, so this is not my problem 
i fill all box. and then i focus it again, now i only touch done button don't edit anything => this is my problem: i can not catch any action or listener
